# Generated by Django 6.0.3 on 2026-07-19 19:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('core_box_id', models.CharField(error_messages={'unique': 'This Core Box ID already exists.'}, max_length=15, unique=True)),
                ('name', models.CharField(error_messages={'unique': 'A Core Box with this Name already exists.'}, max_length=100, unique=True)),
                ('products', models.JSONField(blank=True, default=list)),
                ('core_box_type', models.CharField(choices=[('CO2', 'Co2'), ('OIL', 'Oil'), ('AMINE', 'Amine')], default='CO2', max_length=20)),
                ('total_weight', models.FloatField(default=0.0)),
                ('raw_materials', models.JSONField(blank=True, default=list)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_id', models.CharField(error_messages={'unique': 'This Customer ID already exists.'}, max_length=15, unique=True)),
                ('name', models.CharField(error_messages={'unique': 'A customer with this Name already exists.'}, max_length=100, unique=True)),
                ('code', models.CharField(error_messages={'unique': 'This Customer Code already exists.'}, max_length=15, unique=True)),
                ('gst_number', models.CharField(blank=True, error_messages={'unique': 'This GST Number is already registered.'}, max_length=15, null=True, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('pan', models.CharField(blank=True, error_messages={'unique': 'This PAN is already registered.'}, max_length=10, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatternMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('material_id', models.CharField(error_messages={'unique': 'This Material ID already exists.'}, max_length=15, unique=True)),
                ('name', models.CharField(error_messages={'unique': 'A material with this Name already exists.'}, max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(error_messages={'unique': 'This Material Code already exists.'}, max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Nos', 'Nos'), ('Kg', 'Kg'), ('g', 'g'), ('Pair', 'Pair'), ('Set', 'Set'), ('Box', 'Box'), ('Bag', 'Bag'), ('Can', 'Can'), ('Litre', 'Litre'), ('Millilitre', 'Millilitre'), ('Meter', 'Meter'), ('Centimeter', 'Centimeter'), ('Inch', 'Inch'), ('Packet', 'Packet'), ('Roll', 'Roll'), ('Bottle', 'Bottle'), ('Foot', 'Foot'), ('Square Feet', 'Square Feet'), ('Square Meter', 'Square Meter'), ('Cubic Meter', 'Cubic Meter'), ('Ton', 'Ton'), ('Sheet', 'Sheet'), ('Piece', 'Piece')], default='Kg', max_length=30)),
                ('category', models.CharField(choices=[('PRODUCTION', 'Production'), ('RAW_MATERIAL', 'Raw Material')], default='RAW_MATERIAL', max_length=20)),
                ('departments', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_id', models.CharField(error_messages={'unique': 'This Supplier ID already exists.'}, max_length=15, unique=True)),
                ('name', models.CharField(error_messages={'unique': 'A supplier with this Name already exists.'}, max_length=100, unique=True)),
                ('code', models.CharField(error_messages={'unique': 'This Supplier Code already exists.'}, max_length=15, unique=True)),
                ('gst_number', models.CharField(blank=True, error_messages={'unique': 'This GST Number is already registered.'}, max_length=15, null=True, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('pan', models.CharField(blank=True, error_messages={'unique': 'This PAN is already registered.'}, max_length=10, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoreBoxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_of_entry', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward'), ('INSPECTION', 'Inspection'), ('OUT_FOR_PRODUCTION', 'Out for Production'), ('RETURN_FROM_PRODUCTION', 'Return from Production')], max_length=50)),
                ('description', models.TextField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('core_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.corebox')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='corebox',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coreboxes', to='inventory.customer'),
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('pattern_id', models.CharField(error_messages={'unique': 'This Pattern ID already exists.'}, max_length=15, unique=True)),
                ('products', models.JSONField(blank=True, default=list)),
                ('core_boxes', models.JSONField(blank=True, default=list)),
                ('pattern_type', models.CharField(choices=[('CO2', 'Co2'), ('BLACK_SAND', 'Black Sand')], default='CO2', max_length=20)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patterns', to='inventory.customer')),
                ('bottom_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns_bottom', to='inventory.patternmaterial')),
                ('top_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns_top', to='inventory.patternmaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatternLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_of_entry', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward'), ('INSPECTION', 'Inspection'), ('OUT_FOR_PRODUCTION', 'Out for Production'), ('RETURN_FROM_PRODUCTION', 'Return from Production')], max_length=50)),
                ('description', models.TextField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.pattern')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='corebox',
            name='bottom_core_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coreboxes_bottom', to='inventory.patternmaterial'),
        ),
        migrations.AddField(
            model_name='corebox',
            name='top_core_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coreboxes_top', to='inventory.patternmaterial'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('product_id', models.CharField(error_messages={'unique': 'This Product ID already exists.'}, max_length=15, unique=True)),
                ('name', models.CharField(error_messages={'unique': 'A product with this Name already exists.'}, max_length=100, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='inventory.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStockCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('corrected_quantity', models.FloatField()),
                ('reason', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_correction_logs', to='inventory.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_correction_logs', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialStockCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('corrected_quantity', models.FloatField()),
                ('reason', models.TextField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='material_correction_logs', to='inventory.rawmaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_stocks', to='inventory.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_stocks', to='inventory.product')),
            ],
            options={
                'unique_together': {('customer', 'product', 'batch_no')},
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='material_stocks', to='inventory.rawmaterial')),
            ],
            options={
                'unique_together': {('raw_material', 'batch_no', 'expiry_date')},
            },
        ),
    ]
