# Generated by Django 6.0.3 on 2026-07-18 08:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_endpoint', models.URLField(help_text='The URL React should connect to.', max_length=255)),
                ('db_name', models.CharField(blank=True, max_length=50)),
                ('db_host', models.CharField(default='localhost', max_length=100)),
                ('db_user', models.CharField(default='root', max_length=100)),
                ('db_password', models.CharField(max_length=100)),
                ('db_port', models.IntegerField(default=3306)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_access_dashboard', models.BooleanField(default=True)),
                ('can_access_supplier_master', models.BooleanField(default=False)),
                ('can_access_raw_material_master', models.BooleanField(default=False)),
                ('can_access_customer_master', models.BooleanField(default=False)),
                ('can_access_pattern_material_master', models.BooleanField(default=False)),
                ('can_access_product_master', models.BooleanField(default=False)),
                ('can_access_core_box_master', models.BooleanField(default=False)),
                ('can_access_pattern_master', models.BooleanField(default=False)),
                ('can_access_purchase_inward', models.BooleanField(default=False)),
                ('can_access_purchase_rejection', models.BooleanField(default=False)),
                ('can_access_purchase_return', models.BooleanField(default=False)),
                ('can_access_material_stock', models.BooleanField(default=False)),
                ('can_access_material_stock_log', models.BooleanField(default=False)),
                ('can_access_product_stock', models.BooleanField(default=False)),
                ('can_access_product_stock_log', models.BooleanField(default=False)),
                ('can_access_pattern_flow', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.client')),
            ],
            options={
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('show_customer_to_all_departments', models.BooleanField(default=True)),
                ('show_supplier_to_all_departments', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.client')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_customer_to_all_departments', models.BooleanField(default=True)),
                ('show_supplier_to_all_departments', models.BooleanField(default=True)),
                ('supplier_to_show', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_permission', to='accounts.client')),
            ],
        ),
    ]
