# Generated by Django 6.0.3 on 2026-07-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('inward_number', models.CharField(max_length=20, unique=True)),
                ('inward_date', models.DateField()),
                ('bill_no', models.CharField(max_length=20, unique=True)),
                ('bill_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_inwards', to='inventory.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('gst', models.FloatField(default=18.0)),
                ('cgst', models.FloatField(default=0.0)),
                ('sgst', models.FloatField(default=0.0)),
                ('batch', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinward')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inward_items', to='inventory.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('rejection_number', models.CharField(max_length=20, unique=True)),
                ('rejection_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('purchase_inward', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rejections', to='purchases.purchaseinward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseRejectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('gst', models.FloatField(default=18.0)),
                ('cgst', models.FloatField(default=0.0)),
                ('sgst', models.FloatField(default=0.0)),
                ('purchase_inward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rejection_items', to='purchases.purchaseinwarditem')),
                ('purchase_rejection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaserejection')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rejection_items', to='inventory.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='System', editable=False, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('return_number', models.CharField(max_length=20, unique=True)),
                ('return_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('purchase_inward', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='returns', to='purchases.purchaseinward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('gst', models.FloatField(default=18.0)),
                ('cgst', models.FloatField(default=0.0)),
                ('sgst', models.FloatField(default=0.0)),
                ('purchase_inward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='return_items', to='purchases.purchaseinwarditem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='return_items', to='inventory.rawmaterial')),
            ],
        ),
    ]
